### PR TITLE
Update to Minecraft 1.21.1 (native)

### PR DESCRIPTION
**Pull request by dankfmemes**
Should natively support the latest version of Minecraft now.

### CODE REVIEW

**Comment by dankfmemes** [comment]
This is my first time actually working with Java so let me know if I messed up anything, I'm open to criticism.

**Comment by dankfmemes** [comment]
Actually not sure if I should bump a version number because I noticed it automatically makes an update to itself when I change something.

**Comment by dankfmemes** [comment]
I built this with Eclipse JDK 21

**Comment by lewmilburn** [comment]
Hey, thanks for the addition! I'm about to head off to work so unfortunately can't check this out right now, but I'll take a look when I get home later today, thanks!

**Comment by dankfmemes** [comment]
Commits were just me trying to get the workflows to complete successfully for the merge (because I might not be the best at using the VCS).

**Review by lewmilburn — COMMENTED** [review]
**bug_report.yml** ✅ All good.
**documentation.yml** ✅ All good.
**maven.yml** ✅ All good.
**dependency-reduced-pom.xml** ✅ All good - this is an auto generated file, apparently I just forgot to push the update to GitHub so that's why the plugin version is mismatched, might be overwritten next time it's built but will not cause any issues. (Also see pom.yml comments)
**essence.iml** ✅ All good.
**pom.yml** ❓ Does updating the API version break backwards compatability with 1.20.X? I'm hoping to have as many versions supported as is feasible, and since 1.21.X works with 1.20.X's API, is this needed? If there is a good argument to update I'm happy to, but I'd like to ensure it still works on 1.20.X before merging it. If you're able to test please let me know, if not I'm happy to test it tomorrow.

**Comment by lewmilburn** [comment]
That javadocs thing is driving me wild, it keeps breaking every so often. If you figure out how to get it working that would be amazing! I did ask [here](https://github.com/MathieuSoysal/Javadoc-publisher.yml/issues/87#issuecomment-2369454524) but haven't had chance to properly try it out.

**Pull request merged**
